import { WORK_IMAGE_ALTS, WORK_IMAGES } from "./assets";
import type { WorkFilter, WorkFilterId, WorkProject } from "./types";

export const WORKS_ALL_HREF = "/raboty/";

export const WORK_FILTERS: WorkFilter[] = [
  { id: "all", label: "Все" },
  { id: "profnastil", label: "Профнастил" },
  { id: "metalloshtaketnik", label: "Металлоштакетник" },
  { id: "3d", label: "3D-сетка" },
  { id: "setka", label: "Сварная сетка" },
  { id: "setka-pvh", label: "Сварная сетка ПВХ" },
  { id: "derevyannyy-shtaketnik", label: "Деревянный штакетник" },
];

export const WORK_PROJECTS: WorkProject[] = [
  {
    id: "metalloshtaketnik-svyazist",
    slug: "metalloshtaketnik-svyazist",
    title: "Забор из металлоштакетника шахматкой в СНТ «Связист»",
    city: null,
    location: "СНТ «Связист»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 30,
    height: 1.8,
    color: null,
    material: "металлоштакетник",
    gap: null,
    configuration: "шахматный порядок",
    duration: "2 дня",
    price: 6000,
    priceLabel: "6 000 ₽/м",
    priceNote: "Калитка — в подарок",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.metallSvyazist],
    imageAlt: WORK_IMAGE_ALTS.metallSvyazist,
    description:
      "Металлоштакетник высотой 1,8 м с шахматным заполнением. 30 метров забора установили за 2 дня.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-zaostrovye",
    slug: "metalloshtaketnik-zaostrovye",
    title: "Забор из металлоштакетника в Заостровье",
    city: null,
    location: "Заостровье",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 80,
    height: 1.8,
    color: null,
    material: "металлоштакетник",
    gap: "1 см",
    configuration: null,
    duration: "5 дней",
    price: 4300,
    priceLabel: "4 300 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.metallZaostrovye],
    imageAlt: WORK_IMAGE_ALTS.metallZaostrovye,
    description:
      "80 метров металлоштакетника высотой 1,8 м с зазором 1 см между планками.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-maloe-toynokurye",
    slug: "metalloshtaketnik-maloe-toynokurye",
    title: "Забор из премиум-штакетника в Малом Тойнокурье",
    city: null,
    location: "Малое Тойнокурье",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 20,
    height: 1.5,
    color: null,
    material: "премиум металлоштакетник",
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3800,
    priceLabel: "3 800 ₽/м",
    priceNote: "Калитка — в подарок",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.metallTaynokurye],
    imageAlt: WORK_IMAGE_ALTS.metallTaynokurye,
    description:
      "Забор из премиум металлоштакетника высотой 1,5 м. 20 метров установили за 1 день.",
    layout: "compact",
  },
  {
    id: "profnastil-shirsha",
    slug: "profnastil-shirsha",
    title: "Забор из профнастила под дерево в Ширше",
    city: null,
    location: "Ширша",
    fenceType: "Профнастил",
    filterCategory: "profnastil",
    length: 50,
    height: null,
    color: null,
    material: "двухсторонний профнастил под дерево",
    gap: null,
    configuration: "открытые металлические столбы, чёрный каркас",
    duration: "3 дня",
    price: null,
    priceLabel: "от 4 500 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.profnastilShirsha],
    imageAlt: WORK_IMAGE_ALTS.profnastilShirsha,
    imageObjectPosition: "50% 45%",
    description:
      "50 метров забора из двухстороннего профнастила под дерево с открытыми металлическими столбами и чёрным каркасом.",
    layout: "compact",
  },
  {
    id: "profnastil-snt-sever",
    slug: "profnastil-snt-sever",
    title: "Забор из графитового профлиста с имитацией столбов в СНТ «Север»",
    city: "Северодвинск",
    location: "СНТ «Север»",
    fenceType: "Профнастил",
    filterCategory: "profnastil",
    length: 30,
    height: 1.8,
    color: "графит",
    material: "профлист",
    gap: null,
    configuration: "имитация кирпичных столбов",
    duration: "2 дня",
    price: 3600,
    priceLabel: "3 600 ₽/м",
    priceNote:
      "имитация столбов — стоимость рассчитывается отдельно по месту",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.profnastilSntSever],
    imageAlt: WORK_IMAGE_ALTS.profnastilSntSever,
    imageObjectPosition: "50% 50%",
    description:
      "Графитовый забор из профлиста высотой 1,8 м с декоративной имитацией кирпичных столбов.",
    layout: "compact",
  },
  {
    id: "kombinirovannyy-zabor-snt-pomorochka",
    slug: "kombinirovannyy-zabor-snt-pomorochka",
    title: "Комбинированный забор из профлиста и штакетника в СНТ «Поморочка»",
    city: "Северодвинск",
    location: "СНТ «Поморочка»",
    fenceType: "Профнастил + металлоштакетник",
    filterCategory: "profnastil",
    length: 25,
    height: 1.8,
    color: null,
    material: "профлист и металлический штакетник",
    gap: null,
    configuration: "распашные ворота, калитка — в подарок",
    duration: "1 день",
    price: 3800,
    priceLabel: "3 800 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.profnastilSntPomorochka],
    imageAlt: WORK_IMAGE_ALTS.profnastilSntPomorochka,
    description:
      "Комбинированный забор высотой 1,8 м: профлист и металлический штакетник с распашными воротами.",
    layout: "compact",
  },
  {
    id: "profnastil-pod-derevo-snt-karkul",
    slug: "profnastil-pod-derevo-snt-karkul",
    title: "Забор из профлиста под дерево в СНТ «Каркуль»",
    city: "Северодвинск",
    location: "СНТ «Каркуль»",
    fenceType: "Профнастил",
    filterCategory: "profnastil",
    length: 40,
    height: null,
    color: null,
    material: "профлист с покрытием под дерево",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 4500,
    priceLabel: "4 500 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.profnastilSntKarkul],
    imageAlt: WORK_IMAGE_ALTS.profnastilSntKarkul,
    description:
      "40 метров забора из профлиста с покрытием под дерево. Монтаж выполнили за 2 дня.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-shahmatka-snt-uyma",
    slug: "metalloshtaketnik-shahmatka-snt-uyma",
    title: "Забор из металлоштакетника шахматкой в СНТ «Уйма»",
    city: "Северодвинск",
    location: "СНТ «Уйма»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 54,
    height: null,
    color: null,
    material: "металлоштакетник",
    gap: null,
    configuration: "шахматный порядок, откатные ворота",
    duration: "4 дня",
    price: 6000,
    priceLabel: "6 000 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.metallSntUyma],
    imageAlt: WORK_IMAGE_ALTS.metallSntUyma,
    description:
      "54 метра металлоштакетника в шахматном порядке с откатными воротами.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-shahmatka-snt-dvina",
    slug: "metalloshtaketnik-shahmatka-snt-dvina",
    title: "Забор из металлоштакетника шахматкой в СНТ «Двина»",
    city: "Северодвинск",
    location: "СНТ «Двина»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 42,
    height: null,
    color: null,
    material: "металлоштакетник",
    gap: null,
    configuration: "шахматный порядок, откатные ворота",
    duration: "3 дня",
    price: 6000,
    priceLabel: "6 000 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.metallSntDvina],
    imageAlt: WORK_IMAGE_ALTS.metallSntDvina,
    description:
      "42 метра металлоштакетника в шахматном порядке с откатными воротами.",
    layout: "compact",
  },
  {
    id: "profnastil-kp-rodnik",
    slug: "profnastil-kp-rodnik",
    title: "Забор из профнастила с имитацией кирпичных столбов в КП «Родник»",
    city: null,
    location: "КП «Родник»",
    fenceType: "Профнастил",
    filterCategory: "profnastil",
    length: null,
    height: 1.8,
    color: null,
    material: "профнастил",
    gap: null,
    configuration: "2 ворот, калитка, имитация кирпичных столбов",
    duration: null,
    price: null,
    priceLabel: "от 3 600 ₽/м",
    priceNote:
      "ворота и имитация столбов рассчитываются отдельно. Калитка — в подарок",
    gift: null,
    images: [WORK_IMAGES.profnastilKpRodnik],
    imageAlt: WORK_IMAGE_ALTS.profnastilKpRodnik,
    imageObjectPosition: "50% 42%",
    description:
      "Забор из профнастила высотой 1,8 м с двумя воротами, калиткой и имитацией кирпичных столбов.",
    layout: "compact",
  },
  {
    id: "3d-berezka",
    slug: "3d-berezka",
    title: "Забор из 3D-сетки в СНТ «Берёзка»",
    city: null,
    location: "СНТ «Берёзка»",
    fenceType: "3D-сетка",
    filterCategory: "3d",
    length: 20,
    height: 1.5,
    color: null,
    material: null,
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3000,
    priceLabel: "от 3 000 ₽/м",
    priceNote: "Калитка — в подарок",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.threeDBerezka],
    imageAlt: WORK_IMAGE_ALTS.threeDBerezka,
    description:
      "20 метров зелёного забора из 3D-сетки высотой 1,5 м. Установили за 1 день.",
    layout: "compact",
  },
  {
    id: "3d-ilma",
    slug: "3d-ilma",
    title: "Забор из 3D-сетки в СНТ «Ильма»",
    city: null,
    location: "СНТ «Ильма»",
    fenceType: "3D-сетка",
    filterCategory: "3d",
    length: 20,
    height: 1.5,
    color: null,
    material: null,
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3000,
    priceLabel: "от 3 000 ₽/м",
    priceNote: "Калитка — в подарок",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.threeDIlma],
    imageAlt: WORK_IMAGE_ALTS.threeDIlma,
    description:
      "20 метров забора из 3D-сетки высотой 1,5 м. Монтаж выполнили за 1 день.",
    layout: "compact",
  },
  {
    id: "3d-katuninec",
    slug: "3d-katuninec",
    title: "Графитовый забор из 3D-сетки в СНТ «Катунинец»",
    city: null,
    location: "СНТ «Катунинец»",
    fenceType: "3D-сетка",
    filterCategory: "3d",
    length: 60,
    height: 1.73,
    color: "графит",
    material: null,
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 3300,
    priceLabel: "от 3 300 ₽/м",
    priceNote: "Калитка — в подарок",
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.threeDKatuninec],
    imageAlt: WORK_IMAGE_ALTS.threeDKatuninec,
    description:
      "60 метров забора из 3D-сетки графитового цвета высотой 1,73 м. Установили за 2 дня.",
    layout: "compact",
  },
  {
    id: "setka-ocink",
    slug: "setka-ocink",
    title: "Забор из оцинкованной сварной сетки в Заостровье",
    city: null,
    location: "Заостровье",
    fenceType: "Сварная сетка",
    filterCategory: "setka",
    length: 50,
    height: 1.5,
    color: null,
    material: "сварная оцинкованная сетка",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 2400,
    priceLabel: "от 2 400 ₽/м",
    priceNote: "Материал + монтаж под ключ",
    gift: null,
    images: [WORK_IMAGES.setkaOcink],
    imageAlt: WORK_IMAGE_ALTS.setkaOcink,
    description:
      "50 метров сварной оцинкованной сетки высотой 1,5 м.",
    layout: "compact",
  },
  {
    id: "setka-pvh-25",
    slug: "setka-pvh-25",
    title: "Забор из сварной сетки ПВХ в СНТ «Исток»",
    city: null,
    location: "СНТ «Исток»",
    fenceType: "Сварная сетка",
    filterCategory: "setka-pvh",
    length: 25,
    height: 1.5,
    color: null,
    material: "сварная оцинкованная сетка с ПВХ-покрытием",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 2850,
    priceLabel: "от 2 850 ₽/м",
    priceNote: "Материал + монтаж под ключ",
    gift: null,
    images: [WORK_IMAGES.setkaPvh25],
    imageAlt: WORK_IMAGE_ALTS.setkaPvh25,
    description:
      "25 метров сварной оцинкованной сетки с ПВХ-покрытием высотой 1,5 м.",
    layout: "compact",
  },
  {
    id: "setka-pvh-18",
    slug: "setka-pvh-18",
    title: "Забор из сварной сетки ПВХ в СНТ «Самолёт»",
    city: null,
    location: "СНТ «Самолёт»",
    fenceType: "Сварная сетка",
    filterCategory: "setka-pvh",
    length: 30,
    height: 1.73,
    color: null,
    material: "сварная оцинкованная сетка с ПВХ-покрытием",
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3100,
    priceLabel: "от 3 100 ₽/м",
    priceNote: "Материал + монтаж под ключ",
    gift: null,
    images: [WORK_IMAGES.setkaPvh18],
    imageAlt: WORK_IMAGE_ALTS.setkaPvh18,
    description:
      "30 метров сварной оцинкованной сетки с ПВХ-покрытием высотой 1,73 м.",
    layout: "compact",
  },
  {
    id: "derevyannyy-shtaketnik-zaostrovye",
    slug: "derevyannyy-shtaketnik-zaostrovye",
    title: "Деревянный штакетник в Заостровье",
    city: null,
    location: "Заостровье",
    fenceType: "Деревянный штакетник",
    filterCategory: "derevyannyy-shtaketnik",
    length: 100,
    height: 1.8,
    color: null,
    material: "зазор 2 см",
    gap: "2 см",
    configuration: null,
    duration: "4 дня",
    price: 4000,
    priceLabel: "от 4 000 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.derevyannyyZaostrovye],
    imageAlt: WORK_IMAGE_ALTS.derevyannyyZaostrovye,
    description:
      "Забор из деревянного штакетника высотой 1,8 м. Расстояние между штакетником — 2 см.",
    layout: "compact",
  },
  {
    id: "derevyannyy-shtaketnik-stroitel",
    slug: "derevyannyy-shtaketnik-stroitel",
    title: "Деревянный забор «шахматка» в СНТ «Строитель»",
    city: null,
    location: "СНТ «Строитель»",
    fenceType: "Деревянный штакетник",
    filterCategory: "derevyannyy-shtaketnik",
    length: 30,
    height: 1.8,
    color: null,
    material: "шахматное расположение",
    gap: null,
    configuration: "шахматный порядок",
    duration: "2 дня",
    price: 6000,
    priceLabel: "от 6 000 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.derevyannyyStroitel],
    imageAlt: WORK_IMAGE_ALTS.derevyannyyStroitel,
    description: "Деревянный штакетник установлен в шахматном порядке.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-snt-avtomobilist",
    slug: "metalloshtaketnik-snt-avtomobilist",
    title: "Забор из металлоштакетника в СНТ «Автомобилист»",
    city: "Новодвинск",
    location: "СНТ «Автомобилист»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 30,
    height: 1.8,
    color: "графит",
    material: "металлоштакетник",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 4000,
    priceLabel: "от 4 000 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.novodvinskAvtomobilist],
    imageAlt: WORK_IMAGE_ALTS.novodvinskAvtomobilist,
    description:
      "30 метров графитового металлоштакетника высотой 1,8 м. Установили за 2 дня, калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-snt-druzhba",
    slug: "metalloshtaketnik-snt-druzhba",
    title: "Металлоштакетник с откатными воротами в СНТ «Дружба»",
    city: "Новодвинск",
    location: "СНТ «Дружба»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 25,
    height: 1.8,
    color: "графит",
    material: "металлоштакетник",
    gap: null,
    configuration: "откатные ворота, калитка — в подарок",
    duration: "2 дня",
    price: 4000,
    priceLabel: "от 4 000 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.novodvinskDruzhba],
    imageAlt: WORK_IMAGE_ALTS.novodvinskDruzhba,
    description:
      "25 метров забора из графитового металлоштакетника высотой 1,8 м с откатными воротами. Калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "3d-setka-snt-negino",
    slug: "3d-setka-snt-negino",
    title: "Забор из 3D-сетки в СНТ «Негино»",
    city: "Новодвинск",
    location: "СНТ «Негино»",
    fenceType: "3D-сетка",
    filterCategory: "3d",
    length: 28,
    height: null,
    color: null,
    material: "3D-сетка",
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3000,
    priceLabel: "от 3 000 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.novodvinskNegino],
    imageAlt: WORK_IMAGE_ALTS.novodvinskNegino,
    description: "Установили 28 метров забора из 3D-сетки за один день.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-shahmatka-snt-nadezhda",
    slug: "metalloshtaketnik-shahmatka-snt-nadezhda",
    title: "Забор-шахматка с откатными воротами в СНТ «Надежда»",
    city: "Новодвинск",
    location: "СНТ «Надежда»",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 40,
    height: 1.8,
    color: "шоколад",
    material: "металлоштакетник",
    gap: null,
    configuration: "шахматный порядок, откатные ворота, калитка — в подарок",
    duration: "4 дня",
    price: 6000,
    priceLabel: "от 6 000 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.novodvinskNadezhda],
    imageAlt: WORK_IMAGE_ALTS.novodvinskNadezhda,
    description:
      "40 метров металлоштакетника в шахматном порядке, цвет шоколад. Откатные ворота и калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-derevnya-buty",
    slug: "metalloshtaketnik-derevnya-buty",
    title: "Забор из металлоштакетника в деревне Буты",
    city: "Холмогорский район",
    location: "деревня Буты",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 56,
    height: 1.5,
    color: null,
    material: "металлический штакетник",
    gap: null,
    configuration: "распашные ворота, калитка — в подарок",
    duration: "3 дня",
    price: 3800,
    priceLabel: "3 800 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.holmogoryButy],
    imageAlt: WORK_IMAGE_ALTS.holmogoryButy,
    description:
      "Установили забор из металлического штакетника в деревне Буты Холмогорского района. Общая длина забора — 56 метров. Установили распашные ворота, калитку сделали в подарок.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-derevnya-harlovo",
    slug: "metalloshtaketnik-derevnya-harlovo",
    title: "Забор из металлоштакетника в деревне Харлово",
    city: "Холмогорский район",
    location: "деревня Харлово",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 30,
    height: 1.8,
    color: null,
    material: "металлический штакетник",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 4100,
    priceLabel: "4 100 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.holmogoryHarlovo],
    imageAlt: WORK_IMAGE_ALTS.holmogoryHarlovo,
    description:
      "Смонтировали 30 метров забора из металлического штакетника в деревне Харлово. Высота забора — 1,8 м. Работы выполнили за 2 дня, калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-derevnya-demidovo",
    slug: "metalloshtaketnik-derevnya-demidovo",
    title: "Забор из металлоштакетника в деревне Демидово",
    city: "Холмогорский район",
    location: "деревня Демидово",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 25,
    height: 1.8,
    color: null,
    material: "металлический штакетник",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 4100,
    priceLabel: "4 100 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.holmogoryDemidovo],
    imageAlt: WORK_IMAGE_ALTS.holmogoryDemidovo,
    description:
      "Установили забор из металлического штакетника в деревне Демидово. Длина — 25 метров, высота — 1,8 м. Монтаж занял 2 дня, калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-derevnya-novinki-matigory",
    slug: "metalloshtaketnik-derevnya-novinki-matigory",
    title: "Забор из металлоштакетника в деревне Новинки-Матигоры",
    city: "Холмогорский район",
    location: "деревня Новинки-Матигоры",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 23,
    height: 1.8,
    color: null,
    material: "металлический штакетник",
    gap: null,
    configuration: "ворота, калитка — в подарок",
    duration: "2 дня",
    price: 4100,
    priceLabel: "4 100 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.holmogoryNovinkiMatigory],
    imageAlt: WORK_IMAGE_ALTS.holmogoryNovinkiMatigory,
    description:
      "Смонтировали забор из металлического штакетника в деревне Новинки-Матигоры Холмогорского района. Общая длина — 23 метра, высота — 1,8 м. Установили ворота, калитка — в подарок. Работы выполнили за 2 дня.",
    layout: "compact",
  },
  {
    id: "derevyannyy-shtaketnik-tripuzovo",
    slug: "derevyannyy-shtaketnik-tripuzovo",
    title: "Деревянный забор из штакетника в Трипузово",
    city: "Приморский район",
    location: "Трипузово",
    fenceType: "Деревянный штакетник",
    filterCategory: "derevyannyy-shtaketnik",
    length: 120,
    height: 1.8,
    color: null,
    material: "деревянный штакетник",
    gap: "3 см",
    configuration: "откатные ворота, калитка — в подарок",
    duration: null,
    price: 4000,
    priceLabel: "4 000 ₽/м",
    priceNote: null,
    gift: "Калитка — в подарок",
    images: [WORK_IMAGES.primorskiyTripuzovo],
    imageAlt: WORK_IMAGE_ALTS.primorskiyTripuzovo,
    description:
      "120 метров деревянного штакетника высотой 1,8 м с зазором 3 см. Установлены откатные ворота, калитка — в подарок.",
    layout: "compact",
  },
  {
    id: "3d-setka-laya",
    slug: "3d-setka-laya",
    title: "Забор из 3D-сетки в деревне Лая",
    city: "Приморский район",
    location: "деревня Лая",
    fenceType: "3D-сетка",
    filterCategory: "3d",
    length: 30,
    height: 1.73,
    color: null,
    material: "3D-сетка",
    gap: null,
    configuration: null,
    duration: "1 день",
    price: 3200,
    priceLabel: "3 200 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.primorskiyLaya],
    imageAlt: WORK_IMAGE_ALTS.primorskiyLaya,
    description:
      "30 метров забора из 3D-сетки высотой 1,73 м. Монтаж выполнен за 1 день.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-izhma",
    slug: "metalloshtaketnik-izhma",
    title: "Забор из металлоштакетника в деревне Ижма",
    city: "Приморский район",
    location: "деревня Ижма",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 40,
    height: 1.5,
    color: null,
    material: "металлический штакетник",
    gap: null,
    configuration: null,
    duration: "2 дня",
    price: 3600,
    priceLabel: "3 600 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.primorskiyIzhma],
    imageAlt: WORK_IMAGE_ALTS.primorskiyIzhma,
    description:
      "40 метров металлического штакетника высотой 1,5 м. Работы выполнены за 2 дня.",
    layout: "compact",
  },
  {
    id: "metalloshtaketnik-emelyanovskaya",
    slug: "metalloshtaketnik-emelyanovskaya",
    title: "Забор из металлоштакетника в деревне Емельяновская",
    city: "Приморский район",
    location: "деревня Емельяновская",
    fenceType: "Металлоштакетник",
    filterCategory: "metalloshtaketnik",
    length: 34,
    height: 1.8,
    color: null,
    material: "металлический штакетник",
    gap: "2 см",
    configuration: null,
    duration: "2 дня",
    price: 4300,
    priceLabel: "4 300 ₽/м",
    priceNote: null,
    gift: null,
    images: [WORK_IMAGES.primorskiyEmelyanovskaya],
    imageAlt: WORK_IMAGE_ALTS.primorskiyEmelyanovskaya,
    description:
      "34 метра металлического штакетника высотой 1,8 м с зазором 2 см. Монтаж выполнен за 2 дня.",
    layout: "compact",
  },
];

export function filterWorkProjects(
  projects: WorkProject[],
  filterId: WorkFilterId,
): WorkProject[] {
  if (filterId === "all") {
    return projects;
  }

  return projects.filter((project) => project.filterCategory === filterId);
}

export function getWorkProjectBySlug(slug: string): WorkProject | undefined {
  return WORK_PROJECTS.find((project) => project.slug === slug);
}
